# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: 安装golang环境
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: 构建
      run: go build -v ./...

    - name: 聚合数据
      run: |
        ./tv-aggregation
    - name: 暂存提交
      run: |
        git config --global user.name 'Suleiman'
        git config --global user.email 'Xiayang1900@gmail.com'
        export TZ='Asia/Shanghai'
        git add .
        git commit -m "update" -a
    - name: 推送
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
